root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  docs/updates: changelog
  docs/help-and-guides: /
  docs/developer-api: developers
  docs/genesis-no-code-apps: genesis
  help-center/ai-features: features/ai-features
  api-docs: developers
  automation-guide: automation
  mobile-guide: mobile
  integrations-guide: integrations
  troubleshooting-guide: troubleshooting
  best-practices-guide: best-practices
  enterprise-guide: enterprise-features
  templates-guide: templates
  collaboration-guide: features/collaboration
  ai-agents-guide: features/ai-features/ai-agents-getting-started
  project-views-guide: features/project-views-mastery
  workspace-guide: features/workspaces
  # Genesis-first redirects
  genesis-ai: genesis
  ai-app-builder: genesis
  no-code-platform: genesis
  workspace-dna: features/workspaces
  living-dna: features/workspaces
  tutorial-guide: Taskade-Tutorial
  comprehensive-api: api/comprehensive-api-guide
  industry-solutions: features/industry-solutions
  
  # Archive redirects for simplified structure
  archive/detailed-documentation/advanced-patterns: archive/automation/advanced-patterns
  archive/detailed-documentation/recipes: archive/automation/recipes
  archive/detailed-documentation/triggers: archive/automation/triggers
  archive/detailed-documentation/use-cases: archive/automation/use-cases
  archive/detailed-documentation/industries: archive/business/industries
  archive/detailed-documentation/industry-use-cases: archive/business/industry-use-cases
  archive/detailed-documentation/templates: archive/business/templates
  archive/detailed-documentation/browser-extensions: archive/platform/browser-extensions
  archive/detailed-documentation/enterprise-features: archive/platform/enterprise-features
  archive/detailed-documentation/export: archive/platform/export
  archive/detailed-documentation/import-export: archive/platform/import-export
  archive/detailed-documentation/community: archive/collaboration/community
  archive/detailed-documentation/workspaces: archive/collaboration/workspaces
  archive/detailed-documentation/project-management: archive/collaboration/project-management
  archive/detailed-documentation/best-practices: archive/guides/best-practices
  archive/detailed-documentation/quick-start: archive/guides/quick-start
  archive/detailed-documentation/visual-tutorials: archive/guides/visual-tutorials
  archive/detailed-documentation/integrations: archive/integrations
  archive/detailed-documentation/help-center: archive/help-center

integrations:
  googleAnalytics:
    trackingId: "GA-TRACKING-ID"
  intercom:
    appId: "INTERCOM_APP_ID"
  
git:
  editLinkPattern: 'https://github.com/taskade/docs/edit/main/{{path}}'

customization:
  favicon: .gitbook/assets/ss-api3.png
  logo: .gitbook/assets/ss-api3.png
  
site:
  title: "Taskade Documentation - AI-Powered Productivity Platform"
  description: "Complete guide to Taskade Genesis - build AI apps with one prompt. Master workspaces, automation, AI agents, and the living DNA productivity platform. Transform your ideas into working applications using nothing but plain English."
  
navigation:
  links:
    - title: "🧬 Try Genesis"
      url: "https://www.taskade.com/generate/app"
    - title: "🚀 Launch Taskade"
      url: "https://www.taskade.com/"
    - title: "💻 Developers"
      url: "/developers"
    - title: "📰 Changelog"
      url: "/changelog"
    - title: "🆘 Support"
      url: "https://help.taskade.com/"
    - title: "💬 Community"
      url: "https://www.taskade.com/community"
  
pdf:
  cover: true
  toc: true
  pageBreaks: true
