root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  docs/updates: changelog
  docs/help-and-guides: /  
  docs/developer-api: developers
  docs/genesis-no-code-apps: genesis

integrations:
  googleAnalytics:
    trackingId: "GA-TRACKING-ID"

git:
  editLinkPattern: 'https://github.com/taskade/docs/edit/main/{{path}}'
