root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  docs/updates: changelog
  docs/help-and-guides: /
  docs/developer-api: developers
  docs/genesis-no-code-apps: genesis
  help-center/ai-features: features/ai-features
  api-docs: developers
  automation-guide: automation

integrations:
  googleAnalytics:
    trackingId: "GA-TRACKING-ID"
  intercom:
    appId: "INTERCOM_APP_ID"
  
git:
  editLinkPattern: 'https://github.com/taskade/docs/edit/main/{{path}}'

customization:
  favicon: .gitbook/assets/ss-api3.png
  logo: .gitbook/assets/ss-api3.png
  
site:
  title: "Taskade"
  description: "The productivity platform with living DNA. Your workspace becomes a digital organism where every project, agent, automation, and piece of knowledge connects to form the genetic code of everything you build."
  
navigation:
  links:
    - title: "Main App"
      url: "https://www.taskade.com/"
    - title: "Developers"
      url: "/developers"
    - title: "Changelog" 
      url: "/changelog"
    - title: "Help Center"
      url: "https://help.taskade.com/"
  
pdf:
  cover: true
  toc: true
  pageBreaks: true
